#!/usr/bin/env python
import sys

fontfile = open("3d_font.txt");

charmaps = fontfile.readlines();
alpha = charmaps[0];
charmaps=charmaps[1:]

def index(c):
    return alpha.index(c)

def write(text):
    #lines = [" "*i for i in xrange(0,13)];
    lines = [""]*13;
    tot_max_wid=0
    for c in text:
        ind = index(c)
	
	if ind < 0:
	    print "Character"+ c + " not found in font"
	    return 
        cmap = charmaps[ind*14+1:ind*14+14]
        max_wid = max([len(cmap[i])-i for i in range(0,13)])-1

        for i in range(0,13):
            #spaces=4-i
            new = cmap[i][:-1]
            #new += " "*(max_wid+i-len(new))
            spaces = tot_max_wid-len(lines[i])
            
            if spaces>=0:
                lines[i]+=" "*spaces + new
            else:
                lines[i]+=new[-spaces:]

        tot_max_wid+=max_wid+3
    
    for l in lines:
        print l

if(len(sys.argv) > 1):
    write(sys.argv[1])
else:
    write("hello")
